[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckGracePeriod = 60 
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
HOST = "0.0.0.0"
# Substitua 'mysql' pelo nome do seu serviço de banco de dados se for diferente
DATABASE_URL = "${{ mysql.MYSQL_URL }}"
MYSQLHOST = "${{ mysql.MYSQLHOST }}"
MYSQLPORT = "${{ mysql.MYSQLPORT }}"
MYSQLUSER = "${{ mysql.MYSQLUSER }}"
MYSQLPASSWORD = "${{ mysql.MYSQLPASSWORD }}"
MYSQLDATABASE = "${{ mysql.MYSQLDATABASE }}"
MYSQL_URL = "${{ mysql.MYSQL_URL }}"
